stages:
  - build
  - deploy

variables:
  DEPLOY_PROJECT_NAME: gantrybackend
  IMAGE_TAG: gcr.io/extended-method-356910/gantrybackend:prod

cache:
  paths:
      - ./vendor  

Generate vendor:
  stage: build
  script:
    - |
      if [[ ! -d vendor ]]; then
        docker run --rm -v "$(pwd)":/app --user $(id -u):$(id -g) composer install
      fi
      docker run --rm -v "$(pwd)":/app --user $(id -u):$(id -g) composer update
  only:
    - main
  tags:
    - php-runner

Build:
  stage: build
  before_script:
    - echo $GCP_KEY | base64 -d | docker login -u _json_key --password-stdin https://gcr.io
  script: 
    - docker build -f Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
  tags:
    - php-runner

Deployment: 
  stage: deploy
  script:
    - cp -ar ./* /home/gantryadmin
    - cd /home/gantryadmin
    - docker pull $IMAGE_TAG
    - docker-compose stop app
    - docker-compose up -d
    # - if git diff HEAD^ HEAD ./mysql/mysql.cnf | grep -q mysql; then docker-compose stop db && docker-compose up -d; fi
    # - if git diff HEAD^ HEAD ./nginx/cond.d/app.conf | grep -q nginx; then docker-compose stop webserver && docker-compose up -d; fi
  only:
    - main
  tags:
    - php-runner
