<?php

return [
    'ZOHO_ORG_ID' => env('ZOHO_ORG_ID'),
    'ZOHO_API_CLIENT_SECRET_OFFLINE' => env('ZOHO_API_CLIENT_SECRET_OFFLINE'),
    'ZOHO_API_CLIENT_ID_OFFLINE' => env('ZOHO_API_CLIENT_ID_OFFLINE'),
    'ZOHO_API_REDIRECT_URI_OFFLINE' => env('ZOHO_API_REDIRECT_URI_OFFLINE'),
    'ZOHO_API_REFRESH_TOKEN' => env('ZOHO_API_REFRESH_TOKEN'),
    'ZOHO_API_REGION' => env('ZOHO_API_REGION'),
    'ZOHO_TOKEN' => env('ZOHO_TOKEN'),//token for hooks
];
